import google.generativeai as genai

# Paste your NEW Gemini API key here
API_KEY = "AQ.Ab8RN6LWIoAdZQlbC9-cpMC3j-HTyLO3ySIklBphVNilFQv7iA"

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

with open("outputs/english.txt", "r", encoding="utf-8") as f:
    transcript = f.read()

prompt = f"""
You are an expert in Kannada, Mahabharata, Sanskrit names, and Indian interviews.

The transcript below was generated by speech-to-text software and contains many errors.

Your tasks:

1. Correct obvious transcription mistakes.
2. Correct names of people, places, and Mahabharata terms.
3. Remove repeated phrases.
4. Keep the original meaning.
5. If a sentence is clearly corrupted, rewrite it into the most likely intended meaning.
6. Preserve the interview format.
7. Do NOT invent facts that are not supported by the transcript.
8. Output clean, readable English.

Transcript:

{transcript}
"""

print("🔄 Verifying transcript with Gemini...")

response = model.generate_content(prompt)

clean_text = response.text

with open("outputs/verified_transcript.txt", "w", encoding="utf-8") as f:
    f.write(clean_text)

print("✅ Verified transcript saved!")
print("📄 outputs/verified_transcript.txt")