import google.generativeai as genai
import os

API_KEY = "AQ.Ab8RN6LFGd6b8ufXo6JbOLhXvJ7QZvlrAJ8t_2Cs8xzvTHypjg"

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")


def generate_scenes():

    # Read the story generated by the previous stage
    with open("outputs_v2/story.txt", "r", encoding="utf-8") as f:
        narration = f.read()

    prompt = f"""
You are a professional film director and storyboard artist.

Convert the following documentary story into a sequence of cinematic scenes.

For each scene provide:

- scene_number
- duration_seconds
- visual_description
- camera_movement
- characters
- voiceover

Return ONLY valid JSON.

Story:

{narration}
"""

    print("🎬 Generating scenes...")

    response = model.generate_content(prompt)

    scene_text = response.text

    # Remove markdown if Gemini adds it
    scene_text = scene_text.replace("```json", "").replace("```", "").strip()

    # Make sure the output folder exists
    os.makedirs("outputs_v2", exist_ok=True)

    # Save generated scenes
    with open("outputs_v2/scenes.json", "w", encoding="utf-8") as f:
        f.write(scene_text)

    print("✅ Scenes generated!")
    print("📄 Saved to outputs_v2/scenes.json")

    return "outputs_v2/scenes.json"